openapi: 3.1.0
info:
  title: Personal Blog API
  version: 1.0.0
  description: API endpoints for personal blog with three-column homepage layout

servers:
  - url: http://localhost:3000
    description: Local development server
  - url: https://myblog.example.com
    description: Production server

paths:
  /api/posts:
    get:
      summary: Get paginated list of published blog posts
      description: Returns a paginated list of published posts, ordered by publication date (newest first)
      tags:
        - Posts
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            default: 1
            minimum: 1
          description: Page number for pagination
        - name: limit
          in: query
          schema:
            type: integer
            default: 10
            minimum: 1
            maximum: 50
          description: Number of posts per page
        - name: categoryId
          in: query
          schema:
            type: string
            format: uuid
          description: Filter posts by category ID (optional)
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Post'
                  pagination:
                    $ref: '#/components/schemas/Pagination'
        '400':
          description: Invalid query parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/posts/high-view:
    get:
      summary: Get top posts by view count
      description: Returns posts ordered by view count (highest first) for the center column
      tags:
        - Posts
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            default: 5
            minimum: 1
            maximum: 20
          description: Number of high-view posts to return
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Post'

  /api/posts/{slug}:
    get:
      summary: Get a single post by slug
      description: Returns full post details including markdown content
      tags:
        - Posts
      parameters:
        - name: slug
          in: path
          required: true
          schema:
            type: string
          description: URL-friendly post identifier
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostDetail'
        '404':
          description: Post not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/posts/{slug}/view:
    post:
      summary: Increment post view count
      description: Increments the view count for a specific post (called when user views post)
      tags:
        - Posts
      parameters:
        - name: slug
          in: path
          required: true
          schema:
            type: string
          description: URL-friendly post identifier
      responses:
        '200':
          description: View count incremented
          content:
            application/json:
              schema:
                type: object
                properties:
                  viewCount:
                    type: integer
                    description: Updated view count
        '404':
          description: Post not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/categories:
    get:
      summary: Get all categories with post counts
      description: Returns all categories with the number of published posts in each
      tags:
        - Categories
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Category'

  /api/categories/{slug}:
    get:
      summary: Get a single category by slug
      description: Returns category details and associated posts
      tags:
        - Categories
      parameters:
        - name: slug
          in: path
          required: true
          schema:
            type: string
          description: URL-friendly category identifier
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryDetail'
        '404':
          description: Category not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/profile:
    get:
      summary: Get author profile
      description: Returns blog author's profile information
      tags:
        - Profile
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Author'

components:
  schemas:
    Post:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
          maxLength: 200
        slug:
          type: string
          maxLength: 250
        excerpt:
          type: string
          maxLength: 300
        coverImage:
          type: string
          nullable: true
        publishedAt:
          type: string
          format: date-time
        viewCount:
          type: integer
          minimum: 0
        category:
          type: object
          properties:
            id:
              type: string
              format: uuid
            name:
              type: string
            slug:
              type: string
        author:
          type: object
          properties:
            name:
              type: string
            avatar:
              type: string
              nullable: true
      required:
        - id
        - title
        - slug
        - excerpt
        - publishedAt
        - viewCount
        - category
        - author

    PostDetail:
      allOf:
        - $ref: '#/components/schemas/Post'
        - type: object
          properties:
            content:
              type: string
              description: Full markdown content
            seoTitle:
              type: string
              nullable: true
            seoDescription:
              type: string
              nullable: true
            seoKeywords:
              type: array
              items:
                type: string

    Category:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          maxLength: 50
        slug:
          type: string
          maxLength: 60
        description:
          type: string
          nullable: true
        color:
          type: string
          nullable: true
          pattern: '^#[0-9A-Fa-f]{6}$'
        postCount:
          type: integer
          minimum: 0
          description: Number of published posts in this category
      required:
        - id
        - name
        - slug
        - postCount

    CategoryDetail:
      allOf:
        - $ref: '#/components/schemas/Category'
        - type: object
          properties:
            posts:
              type: array
              items:
                $ref: '#/components/schemas/Post'

    Author:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          maxLength: 100
        email:
          type: string
          format: email
          maxLength: 150
        avatar:
          type: string
          nullable: true
        bio:
          type: string
          description: Author bio in markdown format
        location:
          type: string
          nullable: true
        website:
          type: string
          nullable: true
        socialLinks:
          type: array
          items:
            type: object
            properties:
              platform:
                type: string
                enum: [twitter, github, linkedin, facebook, instagram]
              url:
                type: string
                format: uri
        postCount:
          type: integer
          minimum: 0
          description: Total number of published posts
      required:
        - id
        - name
        - email
        - bio
        - socialLinks

    Pagination:
      type: object
      properties:
        currentPage:
          type: integer
          minimum: 1
        totalPages:
          type: integer
          minimum: 0
        totalItems:
          type: integer
          minimum: 0
        hasNextPage:
          type: boolean
        hasPreviousPage:
          type: boolean
      required:
        - currentPage
        - totalPages
        - totalItems
        - hasNextPage
        - hasPreviousPage

    Error:
      type: object
      properties:
        error:
          type: string
          description: Error message
        code:
          type: string
          description: Error code
        details:
          type: object
          description: Additional error details
      required:
        - error
